#############################################################################
# Makefile for building: Fugesen
# Generated by qmake (2.01a) (Qt 4.8.6) on: ?? 9? 28 10:46:54 2016
# Project:  Fugesen.pro
# Template: app
# Command: /home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/qmake -o Makefile Fugesen.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-linux-gnueabihf-gcc -lts
CXX           = arm-linux-gnueabihf-g++ -lts
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/qws/linux-arm-gnueabi-g++ -I. -I../../WorkDir/HW_Src/libs/qt-4.8.6/include/QtCore -I../../WorkDir/HW_Src/libs/qt-4.8.6/include/QtNetwork -I../../WorkDir/HW_Src/libs/qt-4.8.6/include/QtGui -I../../WorkDir/HW_Src/libs/qt-4.8.6/include/QtSql -I../../WorkDir/HW_Src/libs/qt-4.8.6/include -I. -Ihwlib -I. -I. -I../../WorkDir/HW_Src/libs/tslib-master/include
LINK          = arm-linux-gnueabihf-g++ -lts
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib
LIBS          = $(SUBLIBS)  -L/home/vmuser/WorkDir/HW_Src/libs/tslib-master/lib -L/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib -lQtSql -L/home/vmuser/WorkDir/HW_Src/libs/tslib-master/lib -L/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib -lQtGui -lQtNetwork -lQtCore -lrt -lpthread 
AR            = arm-linux-gnueabihf-ar cqs
RANLIB        = 
QMAKE         = /home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-linux-gnueabihf-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = camera.cpp \
		camera_thread.cpp \
		canread.cpp \
		findlook.cpp \
		main.cpp \
		posix_qextserialport.cpp \
		qextserialbase.cpp \
		signalcan.cpp \
		timesetup.cpp \
		timesetuptrue.cpp \
		videodevice.cpp \
		widget.cpp \
		work.cpp moc_camera.cpp \
		moc_camera_thread.cpp \
		moc_findlook.cpp \
		moc_qextserialbase.cpp \
		moc_signalcan.cpp \
		moc_timesetup.cpp \
		moc_timesetuptrue.cpp \
		moc_videodevice.cpp \
		moc_widget.cpp \
		moc_work.cpp \
		qrc_imagejy.cpp
OBJECTS       = camera.o \
		camera_thread.o \
		canread.o \
		findlook.o \
		main.o \
		posix_qextserialport.o \
		qextserialbase.o \
		signalcan.o \
		timesetup.o \
		timesetuptrue.o \
		videodevice.o \
		widget.o \
		work.o \
		moc_camera.o \
		moc_camera_thread.o \
		moc_findlook.o \
		moc_qextserialbase.o \
		moc_signalcan.o \
		moc_timesetup.o \
		moc_timesetuptrue.o \
		moc_videodevice.o \
		moc_widget.o \
		moc_work.o \
		qrc_imagejy.o
DIST          = ../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/unix.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/linux.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/gcc-base.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/gcc-base-unix.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/g++-base.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/g++-unix.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/qws.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/qconfig.pri \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt_functions.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt_config.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/exclusive_builds.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/default_pre.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/release.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/default_post.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/shared.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/warn_on.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/unix/thread.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/moc.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/resources.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/uic.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/yacc.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/lex.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/include_source_dir.prf \
		Fugesen.pro
QMAKE_TARGET  = Fugesen
DESTDIR       = 
TARGET        = Fugesen

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_findlook.h ui_timesetup.h ui_timesetuptrue.h ui_widget.h ui_work.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Fugesen.pro  ../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/qws/linux-arm-gnueabi-g++/qmake.conf ../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/unix.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/linux.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/gcc-base.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/gcc-base-unix.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/g++-base.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/g++-unix.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/qws.conf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/qconfig.pri \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt_functions.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt_config.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/exclusive_builds.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/default_pre.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/release.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/default_post.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/shared.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/warn_on.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/unix/thread.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/moc.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/resources.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/uic.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/yacc.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/lex.prf \
		../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/include_source_dir.prf \
		/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib/libQtSql.prl \
		/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib/libQtCore.prl \
		/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib/libQtGui.prl \
		/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib/libQtNetwork.prl
	$(QMAKE) -o Makefile Fugesen.pro
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/unix.conf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/linux.conf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/gcc-base.conf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/gcc-base-unix.conf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/g++-base.conf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/g++-unix.conf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/common/qws.conf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/qconfig.pri:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt_functions.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt_config.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/exclusive_builds.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/default_pre.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/release.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/default_post.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/shared.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/warn_on.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/qt.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/unix/thread.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/moc.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/resources.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/uic.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/yacc.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/lex.prf:
../../WorkDir/HW_Src/libs/qt-4.8.6/mkspecs/features/include_source_dir.prf:
/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib/libQtSql.prl:
/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib/libQtCore.prl:
/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib/libQtGui.prl:
/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Fugesen.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Fugesen1.0.0 || $(MKDIR) .tmp/Fugesen1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Fugesen1.0.0/ && $(COPY_FILE) --parents camera.h camera_thread.h canread.h common.h findlook.h mylib.h posix_qextserialport.h qextserialbase.h signalcan.h timesetup.h timesetuptrue.h videodevice.h widget.h work.h hwlib/libdev.h .tmp/Fugesen1.0.0/ && $(COPY_FILE) --parents imagejy.qrc .tmp/Fugesen1.0.0/ && $(COPY_FILE) --parents camera.cpp camera_thread.cpp canread.cpp findlook.cpp main.cpp posix_qextserialport.cpp qextserialbase.cpp signalcan.cpp timesetup.cpp timesetuptrue.cpp videodevice.cpp widget.cpp work.cpp .tmp/Fugesen1.0.0/ && $(COPY_FILE) --parents findlook.ui timesetup.ui timesetuptrue.ui widget.ui work.ui .tmp/Fugesen1.0.0/ && (cd `dirname .tmp/Fugesen1.0.0` && $(TAR) Fugesen1.0.0.tar Fugesen1.0.0 && $(COMPRESS) Fugesen1.0.0.tar) && $(MOVE) `dirname .tmp/Fugesen1.0.0`/Fugesen1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Fugesen1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_camera.cpp moc_camera_thread.cpp moc_findlook.cpp moc_qextserialbase.cpp moc_signalcan.cpp moc_timesetup.cpp moc_timesetuptrue.cpp moc_videodevice.cpp moc_widget.cpp moc_work.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_camera.cpp moc_camera_thread.cpp moc_findlook.cpp moc_qextserialbase.cpp moc_signalcan.cpp moc_timesetup.cpp moc_timesetuptrue.cpp moc_videodevice.cpp moc_widget.cpp moc_work.cpp
moc_camera.cpp: videodevice.h \
		camera.h
	/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/moc $(DEFINES) $(INCPATH) camera.h -o moc_camera.cpp

moc_camera_thread.cpp: camera.h \
		videodevice.h \
		camera_thread.h
	/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/moc $(DEFINES) $(INCPATH) camera_thread.h -o moc_camera_thread.cpp

moc_findlook.cpp: findlook.h
	/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/moc $(DEFINES) $(INCPATH) findlook.h -o moc_findlook.cpp

moc_qextserialbase.cpp: qextserialbase.h
	/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/moc $(DEFINES) $(INCPATH) qextserialbase.h -o moc_qextserialbase.cpp

moc_signalcan.cpp: canread.h \
		signalcan.h
	/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/moc $(DEFINES) $(INCPATH) signalcan.h -o moc_signalcan.cpp

moc_timesetup.cpp: timesetuptrue.h \
		timesetup.h
	/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/moc $(DEFINES) $(INCPATH) timesetup.h -o moc_timesetup.cpp

moc_timesetuptrue.cpp: timesetuptrue.h
	/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/moc $(DEFINES) $(INCPATH) timesetuptrue.h -o moc_timesetuptrue.cpp

moc_videodevice.cpp: videodevice.h
	/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/moc $(DEFINES) $(INCPATH) videodevice.h -o moc_videodevice.cpp

moc_widget.cpp: work.h \
		findlook.h \
		timesetup.h \
		timesetuptrue.h \
		videodevice.h \
		common.h \
		signalcan.h \
		canread.h \
		posix_qextserialport.h \
		qextserialbase.h \
		widget.h
	/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/moc $(DEFINES) $(INCPATH) widget.h -o moc_widget.cpp

moc_work.cpp: findlook.h \
		timesetup.h \
		timesetuptrue.h \
		videodevice.h \
		common.h \
		work.h
	/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/moc $(DEFINES) $(INCPATH) work.h -o moc_work.cpp

compiler_rcc_make_all: qrc_imagejy.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_imagejy.cpp
qrc_imagejy.cpp: imagejy.qrc \
		imagejy/back.png \
		imagejy/timeseticon.png \
		imagejy/setup.png \
		imagejy/jiaozhun.png \
		imagejy/licheng.png \
		imagejy/03-1.png \
		imagejy/qihuan.png \
		imagejy/laba.png \
		imagejy/zw/anjian222.png \
		imagejy/zw/Media.png \
		imagejy/zw/dianhua.png
	/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/rcc -name imagejy imagejy.qrc -o qrc_imagejy.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_findlook.h ui_timesetup.h ui_timesetuptrue.h ui_widget.h ui_work.h
compiler_uic_clean:
	-$(DEL_FILE) ui_findlook.h ui_timesetup.h ui_timesetuptrue.h ui_widget.h ui_work.h
ui_findlook.h: findlook.ui
	/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/uic findlook.ui -o ui_findlook.h

ui_timesetup.h: timesetup.ui
	/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/uic timesetup.ui -o ui_timesetup.h

ui_timesetuptrue.h: timesetuptrue.ui
	/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/uic timesetuptrue.ui -o ui_timesetuptrue.h

ui_widget.h: widget.ui
	/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/uic widget.ui -o ui_widget.h

ui_work.h: work.ui
	/home/vmuser/WorkDir/HW_Src/libs/qt-4.8.6/bin/uic work.ui -o ui_work.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

camera.o: camera.cpp camera.h \
		videodevice.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o camera.cpp

camera_thread.o: camera_thread.cpp camera_thread.h \
		camera.h \
		videodevice.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera_thread.o camera_thread.cpp

canread.o: canread.cpp canread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o canread.o canread.cpp

findlook.o: findlook.cpp findlook.h \
		ui_findlook.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o findlook.o findlook.cpp

main.o: main.cpp widget.h \
		work.h \
		findlook.h \
		timesetup.h \
		timesetuptrue.h \
		videodevice.h \
		common.h \
		signalcan.h \
		canread.h \
		posix_qextserialport.h \
		qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

posix_qextserialport.o: posix_qextserialport.cpp posix_qextserialport.h \
		qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o posix_qextserialport.o posix_qextserialport.cpp

qextserialbase.o: qextserialbase.cpp qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialbase.o qextserialbase.cpp

signalcan.o: signalcan.cpp signalcan.h \
		canread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o signalcan.o signalcan.cpp

timesetup.o: timesetup.cpp timesetup.h \
		timesetuptrue.h \
		ui_timesetup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timesetup.o timesetup.cpp

timesetuptrue.o: timesetuptrue.cpp timesetuptrue.h \
		ui_timesetuptrue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timesetuptrue.o timesetuptrue.cpp

videodevice.o: videodevice.cpp videodevice.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o videodevice.o videodevice.cpp

widget.o: widget.cpp widget.h \
		work.h \
		findlook.h \
		timesetup.h \
		timesetuptrue.h \
		videodevice.h \
		common.h \
		signalcan.h \
		canread.h \
		posix_qextserialport.h \
		qextserialbase.h \
		ui_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

work.o: work.cpp work.h \
		findlook.h \
		timesetup.h \
		timesetuptrue.h \
		videodevice.h \
		common.h \
		ui_work.h \
		camera_thread.h \
		camera.h \
		hwlib/libdev.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o work.o work.cpp

moc_camera.o: moc_camera.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_camera.o moc_camera.cpp

moc_camera_thread.o: moc_camera_thread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_camera_thread.o moc_camera_thread.cpp

moc_findlook.o: moc_findlook.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_findlook.o moc_findlook.cpp

moc_qextserialbase.o: moc_qextserialbase.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qextserialbase.o moc_qextserialbase.cpp

moc_signalcan.o: moc_signalcan.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_signalcan.o moc_signalcan.cpp

moc_timesetup.o: moc_timesetup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_timesetup.o moc_timesetup.cpp

moc_timesetuptrue.o: moc_timesetuptrue.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_timesetuptrue.o moc_timesetuptrue.cpp

moc_videodevice.o: moc_videodevice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_videodevice.o moc_videodevice.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

moc_work.o: moc_work.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_work.o moc_work.cpp

qrc_imagejy.o: qrc_imagejy.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_imagejy.o qrc_imagejy.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

